export let quotes = [
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Aristotle" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Spinoza" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Confucius" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    // { text: "", speaker: "Kierkegaard" },
    { text: "Schools serve the same social functions as prisons and mental institutions- to define, classify, control, and regulate people.", speaker: "Foucault" },
    { text: "Justice must always question itself, just as society can exist only by means of the work it does on itself and on its institutions.", speaker: "Foucault" },
    // { text: "There is no glory in punishing.", speaker: "Foucault" },
    // { text: "The language of psychiatry is a monologue of reason about madness.", speaker: "Foucault" },
    // { text: "People know what they do; they frequently know why they do what they do; but what they don’t know is what what they do does.", speaker: "Foucault" },
    // { text: "I have learned to seek my happiness by limiting my desires, rather than in attempting to satisfy them.", speaker: "John Stuart Mill" },
    // { text: "If all mankind minus one, were of one opinion, and only one person were of the contrary opinion, mankind would be no more justified in silencing that one person, than he, if he had the power, would be justified in silencing mankind.", speaker: "John Stuart Mill" },
    // { text: "It is not because men's desires are strong that they act ill; it is because their consciences are weak.", speaker: "John Stuart Mill" },
    // { text: "Every man who says frankly and fully what he thinks is so far doing a public service. We should be grateful to him for attacking most unsparingly our most cherished opinions.", speaker: "John Stuart Mill" },
    // { text: "Persons of genius, it is true, are, and are always likely to be, a small minority; but in order to have them, it is necessary to preserve the soil in which they grow.", speaker: "John Stuart Mill" },
    // { text: "No one can be a great thinker who does not recognize that as a thinker it is his first duty to follow his intellect to whatever conclusions it may lead.", speaker: "John Stuart Mill" },
    // { text: "The human faculties of perception, judgment, discriminative feeling, mental activity, and even moral preference, are exercised only in making a choice. He who does anything because it is the custom, makes no choice.", speaker: "John Stuart Mill" },
    // { text: "A party of order or stability, and a party of progress or reform, are both necessary elements of a healthy state of political life.", speaker: "John Stuart Mill" },
    // { text: "After the primary necessities of food and raiment, freedom is the first and strongest want of human nature.", speaker: "John Stuart Mill" },
    // { text: "War is an ugly thing, but not the ugliest of things: the decayed and degraded state of moral and patriotic feeling which thinks nothing worth a war, is worse. A man who has nothing which he cares about more than he does about his personal safety is a miserable creature who has no chance of being free, unless made and kept so by the existing of better men than himself.", speaker: "John Stuart Mill" },
    // { text: "The time appears to me to have come when it is the duty of all to make their dissent from religion known.", speaker: "John Stuart Mill" },
    // { text: "No great improvements in the lot of mankind are possible until a great change takes place in the fundamental constitution of their modes of thought.", speaker: "John Stuart Mill" },
    // { text: "He who knows only his own side of the case knows little of that.", speaker: "John Stuart Mill" },
    // { text: "The liberty of the individual must be thus far limited, he must not make himself a nuisance to other people.", speaker: "John Stuart Mill" },
    // { text: "I believe in spectacles, but I think eyes necessary too.", speaker: "John Stuart Mill" },
    // { text: "The things that we love tell us what we are.", speaker: "Thomas Aquinas" },
    // { text: "There is nothing on this earth more to be prized than true friendship.", speaker: "Thomas Aquinas" },
    // { text: "If the highest aim of a captain were to preserve his ship, he would keep it in port forever.", speaker: "Thomas Aquinas" },
    // { text: "Mercy without justice is the mother of dissolution; justice without mercy is cruelty.", speaker: "Thomas Aquinas" },
    // { text: "While injustice is the worst of sins, despair is the most dangerous; because when you are in despair you care neither about yourself nor about others.", speaker: "Thomas Aquinas" },
    // { text: "Beware of the person of one book.", speaker: "Thomas Aquinas" },
    // { text: "The times are never so bad that a good man cannot live in them.", speaker: "Thomas Aquinas" },
    // { text: "Better to illuminate than merely to shine, to deliver to others contemplated truths than merely to contemplate.", speaker: "Thomas Aquinas" },
    // { text: "The philosophers have only interpreted the world, in various ways. The point, however, is to change it.", speaker: "Marx" },
    // { text: "The oppressed are allowed once every few years to decide which particular representatives of the oppressing class are to represent and repress them.", speaker: "Marx" },
    // { text: "Surround yourself with people who make you happy. People who make you laugh, who help you when you’re in need. People who genuinely care. They are the ones worth keeping in your life. Everyone else is just passing through.", speaker: "Marx" },
    // { text: "The last capitalist we hang shall be the one who sold us the rope.", speaker: "Marx" },
    // { text: "To be radical is to go to the root of the matter. For man, however, the root is man himself.", speaker: "Marx" },
    // { text: "Go on, get out! Last words are for fools who haven't said enough!", speaker: "Marx" },
    // { text: "Religion is the impotence of the human mind to deal with occurrences it cannot understand.", speaker: "Marx" },
    // { text: "The tradition of all dead generations weighs like a nightmare on the brains of the living.", speaker: "Marx" },
    // { text: "Communism is the riddle of history solved, and it knows itself to be this solution.", speaker: "Marx" },
    // { text: "The increase in value of the world of things is directly proportional to the decrease in value of the human world.", speaker: "Marx" },
    // { text: "The production of too many useful things results in too many useless people.", speaker: "Marx" },
    // { text: "The road to hell is paved with good intentions.", speaker: "Marx" },
    // { text: "Necessity is blind until it becomes conscious. Freedom is the consciousness of necessity.", speaker: "Marx" },
    // { text: "Political power, properly so called, is merely the organised power of one class for oppressing another.", speaker: "Marx" },
    // { text: "Social progress can be measured by the social position of the female sex.", speaker: "Marx" },
    // { text: "You must be aware that the reward for labour, and quantity of labour, are quite disparate things.", speaker: "Marx" },
    // { text: "Religion is the sigh of the oppressed creature, the heart of a heartless world, just as it is the spirit of a spiritless situation. It is the opium of the people.", speaker: "Marx" },
    // { text: "The demand to give up the illusions about its condition is the demand to give up a condition that needs illusions.", speaker: "Marx" },
    // { text: "From each according to their ability, to each according to their need.", speaker: "Marx" },
    // { text: "Ignorance never yet helped anybody.", speaker: "Marx" },
    // { text: "Love truth, but pardon error.", speaker: "Voltaire" },
    // { text: "Let us read, and let us dance; these two amusements will never do any harm to the world.", speaker: "Voltaire" },
    // { text: "Judge a man by his questions rather than by his answers.", speaker: "Voltaire" },
    // { text: "It is forbidden to kill; therefore all murderers are punished unless they kill in large numbers and to the sound of trumpets.", speaker: "Voltaire" },
    // { text: "Life is a shipwreck, but we must not forget to sing in the lifeboats.", speaker: "Voltaire" },
    // { text: "Those who can make you believe absurdities, can make you commit atrocities.", speaker: "Voltaire" },
    // { text: "The more I read, the more I acquire, the more certain I am that I know nothing.", speaker: "Voltaire" },
    // { text: "God is a comedian playing to an audience that is too afraid to laugh.", speaker: "Voltaire" },
    // { text: "Dare to think for yourself.", speaker: "Voltaire" },
    // { text: "The most important decision you make is to be in a good mood.", speaker: "Voltaire" },
    // { text: "Doubt is an uncomfortable condition, but certainty is a ridiculous one.", speaker: "Voltaire" },
    // { text: "Cherish those who seek the truth but beware of those who find it.", speaker: "Voltaire" },
    // { text: "It is better to risk saving a guilty person than to condemn an innocent one.", speaker: "Voltaire" },
    // { text: "The best answer to anger is silence.", speaker: "Marcus Aurelius" },
    // { text: "The best revenge is not to be like your enemy.", speaker: "Marcus Aurelius" },
    // { text: "Confine yourself to the present.", speaker: "Marcus Aurelius" },
    // { text: "The more we value things outside our control, the less control we have.", speaker: "Marcus Aurelius" },
    // { text: "How ridiculous and how strange to be surprised at anything which happens in life.", speaker: "Marcus Aurelius" },
    // { text: "You have power over your mind – not outside events. Realize this, and you will find strength.", speaker: "Marcus Aurelius" },
    // { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.", speaker: "Marcus Aurelius" },
    // { text: "When you arise in the morning, think of what a precious privilege it is to be alive – to breathe, to think, to enjoy, to love.", speaker: "Marcus Aurelius" },
    // { text: "You can commit injustice by doing nothing.", speaker: "Marcus Aurelius" },
    // { text: "Waste no more time arguing about what a good man should be. Be one.", speaker: "Marcus Aurelius" },
    // { text: "Each day provides its own gifts.", speaker: "Marcus Aurelius" },
    // { text: "Give yourself a gift, the present moment.", speaker: "Marcus Aurelius" },
    // { text: "The only wealth which you will keep forever is the wealth you have given away.", speaker: "Marcus Aurelius" },
    // { text: "Have I been made for this, to lie under the blankets and keep myself warm?", speaker: "Marcus Aurelius" },
    // { text: "Conceal a flaw, and the world will imagine the worst.", speaker: "Marcus Aurelius" },
    // { text: "Life is neither good or evil, but only a place for good and evil.", speaker: "Marcus Aurelius" },
    // { text: "I cannot escape death, but at least I can escape the fear of it.", speaker: "Marcus Aurelius" },
    // { text: "How trivial the things we want so passionately are.", speaker: "Marcus Aurelius" },
    // { text: "Settle on the type of person you want to be and stick to it, whether alone or in company.", speaker: "Marcus Aurelius" },
    // { text: "Consider at what price you sell your integrity, but please, for God’s sake, don’t sell it cheap.", speaker: "Marcus Aurelius" },
    // { text: "Life, if well lived, is long enough.", speaker: "Seneca" },
    // { text: "Everywhere is nowhere. When a person spends all his time in foreign travel, he ends by having many acquaintances, but no friends.", speaker: "Seneca" },
    // { text: "While we are postponing, life speeds by", speaker: "Seneca" },
    // { text: "We suffer more often in imagination than in reality.", speaker: "Seneca" },
    // { text: "Ignorance is the cause of fear.", speaker: "Seneca" },
    // { text: "Life is long, if you know how to use it.", speaker: "Seneca" },
    // { text: "Hurry up and live.", speaker: "Seneca" },
    // { text: "Cease to hope and you will cease to fear.", speaker: "Seneca" },
    // { text: "Wealth is the slave of a wise man and the master of a fool.", speaker: "Seneca" },
    // { text: "Only time can heal what reason cannot.", speaker: "Seneca" },
    // { text: "Hang on to your youthful enthusiasms, you will be able to use them better when you are older.", speaker: "Seneca" },
    // { text: "He who is brave is free.", speaker: "Seneca" },
    // { text: "It is a rough road that leads to the heights of greatness.", speaker: "Seneca" },
    // { text: "It is more civilized to make fun of life than to bewail it.", speaker: "Seneca" },
    // { text: "Difficulty comes from our lack of confidence.", speaker: "Seneca" },
    // { text: "Life is very short and anxious for those who forget the past, neglect the present, and fear the future.", speaker: "Seneca" },
    // { text: "What really ruins our character is the fact that none of us looks back over his life.", speaker: "Seneca" },
    // { text: "Religion is regarded by the common people as true, by the wise as false, and by rulers as useful.", speaker: "Seneca" },
    // { text: "It does not matter how many books you have, but how good are the books which you have.", speaker: "Seneca" },
    // { text: "When a person spends all his time in foreign travel, he ends by having many acquaintances, but no friends.", speaker: "Seneca" },
    // { text: "The greatest remedy for anger is delay.", speaker: "Seneca" },
    // { text: "For many men, the acquisition of wealth does not end their troubles, it only changes them.", speaker: "Seneca" },
    // { text: "We have two ears and one mouth so that we can listen twice as much as we speak.", speaker: "Epictetus" },
    // { text: "No man is free who is not master of himself.", speaker: "Epictetus" },
    // { text: "Men are disturbed not by things, but by the view which they take of them.", speaker: "Epictetus" },
    // { text: "It is difficulties that show what men are.", speaker: "Epictetus" },
    // { text: "Make the best use of what is in your power, and take the rest as it happens.", speaker: "Epictetus" },
    // { text: "A ship should not ride on a single anchor, nor life on a single hope.", speaker: "Epictetus" },
    // { text: "No great thing is created suddenly.", speaker: "Epictetus" },
    // { text: "Know, first, who you are, and then adorn yourself accordingly.", speaker: "Epictetus" },
    // { text: "It is the nature of the wise to resist pleasures, but the foolish to be a slave to them.", speaker: "Epictetus" },
    // { text: "First learn the meaning of what you say, and then speak.", speaker: "Epictetus" },
    // { text: "If you want something good, get it yourself.", speaker: "Epictetus" },
    // { text: "All the good are friends of one another.", speaker: "Zeno" },
    // { text: "No loss should be more regrettable to us than losing our time, for it’s irretrievable.", speaker: "Zeno" },
    // { text: "Extravagance is its own destroyer.", speaker: "Zeno" },
    // { text: "Man conquers the world by conquering himself.", speaker: "Zeno" },
    // { text: "Steel your sensibilities, so that life shall hurt you as little as possible.", speaker: "Zeno" },
    // { text: "Better to trip with the feet than with the tongue.", speaker: "Zeno" },
    // { text: "A bad feeling is a commotion of the mind repugnant to reason, and against nature.", speaker: "Zeno" },
    // { text: "We begin to lose our hesitation to do immoral things when we lose our hesitation to speak of them.", speaker: "Musonius Rufus" },
    // { text: "Humanity must seek what is NOT simple and obvious using the simple and obvious.", speaker: "Musonius Rufus" },
    // { text: "Since every man dies, it is better to die with distinction than to live long.", speaker: "Musonius Rufus" },
    // { text: "Only by exhibiting actions in harmony with the sound words which he has received will anyone be helped by philosophy.", speaker: "Musonius Rufus" },
    // { text: "Thus whoever destroys human marriage destroys the home, the city-the whole human race.", speaker: "Musonius Rufus" },
    // { text: "He with the most who is content with the least.", speaker: "Diogenes" },
    // { text: "The foundation of every state is the education of its youth.", speaker: "Diogenes" },
    // { text: "Blushing is the color of virtue.", speaker: "Diogenes" },
    // { text: "I am not an Athenian or a Greek, but a citizen of the world.", speaker: "Diogenes" },
    // { text: "The mob is the mother of tyrants.", speaker: "Diogenes" },
    // { text: "Poverty is a virtue which one can teach oneself.", speaker: "Diogenes" },
    // { text: "Beauty is no quality in things themselves: It exists merely in the mind which contemplates them; and each mind perceives a different beauty.", speaker: "Hume" },
    // { text: "No man ever threw away life while it was worth keeping.", speaker: "Hume" },
    // { text: "But the life of a man is of no greater importance to the universe than that of an oyster.", speaker: "Hume" },
    // { text: "He is happy whose circumstances suit his temper, but he is more excellent who can suit his temper to his circumstance.", speaker: "Hume" },
    // { text: "It is an absurdity to believe that the Deity has human passions, and one of the lowest of human passions, a restless appetite for applause.", speaker: "Hume" },
    // { text: "The sweetest and most inoffensive path of life leads through the avenues of science and learning; and whoever can either remove any obstructions in this way, or open up any new prospect, ought so far to be esteemed a benefactor to mankind.", speaker: "Hume" },
    // { text: "Stercus accidit.", speaker: "Hume" },
    // { text: "Any pride or haughtiness, is displeasing to us, merely because it shocks our own pride, and leads us by sympathy into comparison, which causes the disagreeable passion of humility.", speaker: "Hume" },
    // { text: "To philosopher and historian the madness and imbecile wickedness of mankind ought to appear ordinary events.", speaker: "Hume" },
    // { text: "It is seldom that liberty of any kind is lost all at once.", speaker: "Hume" },
    // { text: "Men's views of things are the result of their understanding alone. Their conduct is regulated by their understanding, their temper, and their passions.", speaker: "Hume" },
    // { text: "As every inquiry which regards religion is of the utmost importance, there are two questions in particular which challenge our attention, to wit, that concerning its foundation in reason, and that concerning it origin in human nature.", speaker: "Hume" },
    // { text: "All knowledge degenerates into probability.", speaker: "Hume" },
    // { text: "The Crusades - the most signal and most durable monument of human folly that has yet appeared in any age or nation.", speaker: "Hume" },
    // { text: "The bigotry of theologians [is] a malady which seems almost incurable.", speaker: "Hume" },
    // { text: "It is difficult for a man to speak long of himself without vanity.", speaker: "Hume" },
    // { text: "The gazing populace receive greedily, without examination, whatever soothes superstition and promotes wonder.", speaker: "Hume" },
    // { text: "What a peculiar privilege has this little agitation of the brain which we call 'thought'.", speaker: "Hume" },
    // { text: "Long before we have reached the last steps of the argument leading to our theory, we are already in Fairyland.", speaker: "Hume" },
    // { text: "There is no craving or demand of the human mind more constant and insatiable than that for exercise and employment, and this desire seems the foundation of most of our passions and pursuits.", speaker: "Hume" },
    // { text: "We are not rich by what we possess but by what we can do without.", speaker: "Kant" },
    // { text: "He who is cruel to animals becomes hard also in his dealings with men. We can judge the heart of a man by his treatment of animals.", speaker: "Kant" },
    // { text: "I had to deny knowledge in order to make room for faith.", speaker: "Kant" },
    // { text: "One who makes himself a worm cannot complain afterwards if people step on him.", speaker: "Kant" },
    // { text: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason.", speaker: "Kant" },
    // { text: "Rules for happiness: something to do, someone to love, something to hope for.", speaker: "Kant" },
    // { text: "For peace to reign on Earth, humans must evolve into new beings who have learned to see the whole first.", speaker: "Kant" },
    // { text: "The busier we are, the more acutely we feel that we live, the more conscious we are of life.", speaker: "Kant" },
    // { text: "Space and time are the framework within which the mind is constrained to construct its experience of reality.", speaker: "Kant" },
    // { text: "If the truth shall kill them, let them die.", speaker: "Kant" },
    // { text: "Man must be disciplined, for he is by nature raw and wild..", speaker: "Kant" },
    // { text: "The only true wisdom is in knowing you know nothing.", speaker: "Socrates" },
    // { text: "The unexamined life is not worth living.", speaker: "Socrates" },
    // { text: "I cannot teach anybody anything. I can only make them think.", speaker: "Socrates" },
    // { text: "There is only one good, knowledge, and one evil, ignorance.", speaker: "Socrates" },
    // { text: "Be kind, for everyone you meet is fighting a hard battle.", speaker: "Socrates" },
    // { text: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", speaker: "Socrates" },
    // { text: "Wonder is the beginning of wisdom.", speaker: "Socrates" },
    // { text: "To find yourself, think for yourself.", speaker: "Socrates" },
    // { text: "Education is the kindling of a flame, not the filling of a vessel.", speaker: "Socrates" },
    // { text: "He who is not contented with what he has, would not be contented with what he would like to have.", speaker: "Socrates" },
    // { text: "Be slow to fall into friendship, but when you are in, continue firm and constant.", speaker: "Socrates" },
    // { text: "If you don't get what you want, you suffer; if you get what you don't want, you suffer; even when you get exactly what you want, you still suffer because you can't hold on to it forever. Your mind is your predicament. It wants to be free of change. Free of pain, free of the obligations of life and death. But change is law and no amount of pretending will alter that reality.", speaker: "Socrates" },
    // { text: "Sometimes you put walls up not to keep people out, but to see who cares enough to break them down.", speaker: "Socrates" },
    // { text: "My friend...care for your psyche...know thyself, for once we know ourselves, we may learn how to care for ourselves", speaker: "Socrates" },
    // { text: "Let him who would move the world first move himself.", speaker: "Socrates" },
    // { text: "Contentment is natural wealth, luxury is artificial poverty.", speaker: "Socrates" },
    // { text: "To fear death, gentlemen, is no other than to think oneself wise when one is not, to think one knows what one does not know. No one knows whether death may not be the greatest of all blessings for a man, yet men fear it as if they knew that it is the greatest of evils.", speaker: "Socrates" },
    // { text: "Employ your time in improving yourself by other men's writings so that you shall come easily by what others have labored hard for.", speaker: "Socrates" },
    // { text: "Do not do to others what angers you if done to you by others.", speaker: "Socrates" },
    // { text: "Every action has its pleasures and its price.", speaker: "Socrates" },
    // { text: "We cannot live better than in seeking to become better.", speaker: "Socrates" },
    // { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", speaker: "Socrates" },
    // { text: "Understanding a question is half an answer", speaker: "Socrates" },
    // { text: "Be as you wish to seem.", speaker: "Socrates" },
    // { text: "Thou shouldst eat to live; not live to eat.", speaker: "Socrates" },
    // { text: "One should never do wrong in return, nor mistreat any man, no matter how one has been mistreated by him.", speaker: "Socrates" },
    // { text: "The really important thing is not to live, but to live well. And to live well meant, along with more enjoyable things in life, to live according to your principles.", speaker: "Socrates" },
    // { text: "The easiest and noblest way is not to be crushing others, but to be improving yourselves.", speaker: "Socrates" },
    // { text: "If all our misfortunes were laid in one common heap whence everyone must take an equal portion, most people would be content to take their own and depart.", speaker: "Socrates" },
    // { text: "Those who are hardest to love need it the most.", speaker: "Socrates" },
    // { text: "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", speaker: "Nietzsche" },
    // { text: "That which does not kill us makes us stronger.", speaker: "Nietzsche" },
    // { text: "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.", speaker: "Nietzsche" },
    // { text: "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.", speaker: "Nietzsche" },
    // { text: "You have your way. I have my way. As for the right way, the correct way, and the only way, it does not exist.", speaker: "Nietzsche" },
    // { text: "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.", speaker: "Nietzsche" },
    // { text: "He who has a why to live for can bear almost any how.", speaker: "Nietzsche" },
    // { text: "When we are tired, we are attacked by ideas we conquered long ago.", speaker: "Nietzsche" },
    // { text: "I cannot believe in a God who wants to be praised all the time.", speaker: "Nietzsche" },
    // { text: "The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind.", speaker: "Nietzsche" },
    // { text: "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.", speaker: "Nietzsche" },
    // { text: "No one can construct for you the bridge upon which precisely you must cross the stream of life, no one but you yourself alone.", speaker: "Nietzsche" },
    // { text: "Is man merely a mistake of God's? Or God merely a mistake of man?", speaker: "Nietzsche" },
    // { text: "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.", speaker: "Nietzsche" },
    // { text: "Man is the cruelest animal.", speaker: "Nietzsche" },
    // { text: "Every deep thinker is more afraid of being understood than of being misunderstood.", speaker: "Nietzsche" },
    // { text: "Thoughts are the shadows of our feelings -- always darker, emptier and simpler.", speaker: "Nietzsche" },
    // { text: "A thinker sees his own actions as experiments and questions--as attempts to find out something. Success and failure are for him answers above all.", speaker: "Nietzsche" },
    // { text: "The true man wants two things: danger and play. For that reason he wants woman, as the most dangerous plaything.", speaker: "Nietzsche" },
    // { text: "There are two different types of people in the world, those who want to know, and those who want to believe.", speaker: "Nietzsche" },
    // { text: "All things are subject to interpretation. Whichever interpretation prevails at a given time is a function of power and not truth.", speaker: "Nietzsche" },
    // { text: "Silence is worse; all truths that are kept silent become poisonous.", speaker: "Nietzsche" },
    // { text: "Meaning and morality of One's life come from within oneself. Healthy, strong individuals seek self expansion by experimenting and by living dangerously. Life consists of an infinite number of possibilities and the healthy person explores as many of them as posible. Religions that teach pity, self-contempt, humility, self-restraint and guilt are incorrect. The good life is ever changing, challenging, devoid of regret, intense, creative and risky.", speaker: "Nietzsche" },
    // { text: "What does your conscience say? — 'You should become the person you are'", speaker: "Nietzsche" },
    // { text: "To live is to suffer, to survive is to find some meaning in the suffering.", speaker: "Nietzsche" },
    // { text: "Of all forms of caution, caution in love is perhaps the most fatal to true happiness.", speaker: "Bertrand Russell" },
    // { text: "The fundamental cause of the trouble is that in the modern world the stupid are cocksure while the intelligent are full of doubt.", speaker: "Bertrand Russell" },
    // { text: "I would never die for my beliefs because I might be wrong.", speaker: "Bertrand Russell" },
    // { text: "And if there were a God, I think it very unlikely that He would have such an uneasy vanity as to be offended by those who doubt His existence", speaker: "Bertrand Russell" },
    // { text: "Three passions, simple but overwhelmingly strong have governed my life: the longing for love, the search for knowledge, and unbearable pity for the suffering of mankind.", speaker: "Bertrand Russell" },
    // { text: "In all affairs it's a healthy thing now and then to hang a question mark on the things you have long taken for granted.", speaker: "Bertrand Russell" },
    // { text: "One of the symptoms of an approaching nervous breakdown is the belief that one’s work is terribly important.", speaker: "Bertrand Russell" },
    // { text: "The hardest thing to learn in life is which bridge to cross and which to burn.", speaker: "Bertrand Russell" },
    // { text: "Fear is the main source of superstition, and one of the main sources of cruelty. To conquer fear is the beginning of wisdom.", speaker: "Bertrand Russell" },
    // { text: "It's easy to fall in love. The hard part is finding someone to catch you.", speaker: "Bertrand Russell" },
    // { text: "To teach how to live without certainty, and yet without being paralyzed by hesitation, is perhaps the chief thing that philosophy, in our age, can still do for those who study it.", speaker: "Bertrand Russell" },
    // { text: "It is the preoccupation with possessions, more than anything else, that prevents us from living freely and nobly.", speaker: "Bertrand Russell" },
    // { text: "When you want to teach children to think, you begin by treating them seriously when they are little, giving them responsibilities, talking to them candidly, providing privacy and solitude for them, and making them readers and thinkers of significant thoughts from the beginning. That’s if you want to teach them to think.", speaker: "Bertrand Russell" },
    // { text: "Those who have never known the deep intimacy and the intense companionship of happy mutual love have missed the best thing that life has to give.", speaker: "Bertrand Russell" },
    // { text: "Collective fear stimulates herd instinct, and tends to produce ferocity toward those who are not regarded as members of the herd.", speaker: "Bertrand Russell" },
    // { text: "We know very little, and yet it is astonishing that we know so much, and still more astonishing that so little knowledge can give us so much power.", speaker: "Bertrand Russell" },
    // { text: "It has been said that man is a rational animal. All my life I have been searching for evidence which could support this.", speaker: "Bertrand Russell" },
    // { text: "One should as a rule respect public opinion in so far as is necessary to avoid starvation and to keep out of prison, but anything that goes beyond this is voluntary submission to an unnecessary tyranny, and is likely to interfere with happiness in all kinds of ways.", speaker: "Bertrand Russell" },
    // { text: "The secret of happiness is to face the fact that the world is horrible, horrible, horrible.", speaker: "Bertrand Russell" },
    // { text: "The fact that an opinion has been widely held is no evidence whatever that it is not utterly absurd; indeed in view of the silliness of the majority of mankind, a widely spread belief is more likely to be foolish than sensible.", speaker: "Bertrand Russell" },
    // { text: "I believe that when I die I shall rot, and nothing of my ego will survive.", speaker: "Bertrand Russell" },
    // { text: "Patriots always talk of dying for their country but never of killing for their country.", speaker: "Bertrand Russell" },
    // { text: "The infliction of cruelty with a good conscience is a delight to moralists. That is why they invented Hell.", speaker: "Bertrand Russell" },
    // { text: "Not to be absolutely certain is, I think, one of the essential things in rationality.", speaker: "Bertrand Russell" },
    // { text: "So far as I can remember there is not one word in the Gospels in praise of intelligence.", speaker: "Bertrand Russell" },
    // { text: "The opinions that are held with passion are always those for which no good ground exists; indeed the passion is the measure of the holders lack of rational conviction. Opinions in politics and religion are almost always held passionately.", speaker: "Bertrand Russell" }
];