export let quotes = [
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "", speaker: "Marx" },
    { text: "Love truth, but pardon error.", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "", speaker: "Voltaire" },
    { text: "The best answer to anger is silence.", speaker: "Marcus Aurelius" },
    // { text: "The best revenge is not to be like your enemy.", speaker: "Marcus Aurelius" },
    // { text: "Confine yourself to the present.", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    { text: "", speaker: "Marcus Aurelius" },
    // { text: "Life, if well lived, is long enough.", speaker: "Seneca" },
    // { text: "Everywhere is nowhere. When a person spends all his time in foreign travel, he ends by having many acquaintances, but no friends.", speaker: "Seneca" },
    // { text: "While we are postponing, life speeds by", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Seneca" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Epictetus" },
    { text: "", speaker: "Zeno" },
    { text: "", speaker: "Zeno" },
    { text: "", speaker: "Zeno" },
    { text: "", speaker: "Zeno" },
    { text: "", speaker: "Zeno" },
    { text: "", speaker: "Zeno" },
    { text: "", speaker: "Zeno" },
    { text: "", speaker: "Musonius Rufus" },
    { text: "", speaker: "Musonius Rufus" },
    { text: "", speaker: "Musonius Rufus" },
    { text: "", speaker: "Musonius Rufus" },
    { text: "", speaker: "Musonius Rufus" },
    { text: "", speaker: "Diogenes" },
    { text: "", speaker: "Diogenes" },
    { text: "", speaker: "Diogenes" },
    { text: "", speaker: "Diogenes" },
    { text: "", speaker: "Diogenes" },
    { text: "", speaker: "Diogenes" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    { text: "", speaker: "Hume" },
    // { text: "We are not rich by what we possess but by what we can do without.", speaker: "Kant" },
    // { text: "He who is cruel to animals becomes hard also in his dealings with men. We can judge the heart of a man by his treatment of animals.", speaker: "Kant" },
    // { text: "I had to deny knowledge in order to make room for faith.", speaker: "Kant" },
    // { text: "One who makes himself a worm cannot complain afterwards if people step on him.", speaker: "Kant" },
    // { text: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason.", speaker: "Kant" },
    // { text: "Rules for happiness: something to do, someone to love, something to hope for.", speaker: "Kant" },
    // { text: "For peace to reign on Earth, humans must evolve into new beings who have learned to see the whole first.", speaker: "Kant" },
    // { text: "The busier we are, the more acutely we feel that we live, the more conscious we are of life.", speaker: "Kant" },
    // { text: "Space and time are the framework within which the mind is constrained to construct its experience of reality.", speaker: "Kant" },
    // { text: "If the truth shall kill them, let them die.", speaker: "Kant" },
    // { text: "Man must be disciplined, for he is by nature raw and wild..", speaker: "Kant" },
    // { text: "The only true wisdom is in knowing you know nothing.", speaker: "Socrates" },
    // { text: "The unexamined life is not worth living.", speaker: "Socrates" },
    // { text: "I cannot teach anybody anything. I can only make them think.", speaker: "Socrates" },
    // { text: "There is only one good, knowledge, and one evil, ignorance.", speaker: "Socrates" },
    // { text: "Be kind, for everyone you meet is fighting a hard battle.", speaker: "Socrates" },
    // { text: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", speaker: "Socrates" },
    // { text: "Wonder is the beginning of wisdom.", speaker: "Socrates" },
    // { text: "To find yourself, think for yourself.", speaker: "Socrates" },
    // { text: "Education is the kindling of a flame, not the filling of a vessel.", speaker: "Socrates" },
    // { text: "He who is not contented with what he has, would not be contented with what he would like to have.", speaker: "Socrates" },
    // { text: "Be slow to fall into friendship, but when you are in, continue firm and constant.", speaker: "Socrates" },
    // { text: "If you don't get what you want, you suffer; if you get what you don't want, you suffer; even when you get exactly what you want, you still suffer because you can't hold on to it forever. Your mind is your predicament. It wants to be free of change. Free of pain, free of the obligations of life and death. But change is law and no amount of pretending will alter that reality.", speaker: "Socrates" },
    // { text: "Sometimes you put walls up not to keep people out, but to see who cares enough to break them down.", speaker: "Socrates" },
    // { text: "My friend...care for your psyche...know thyself, for once we know ourselves, we may learn how to care for ourselves", speaker: "Socrates" },
    // { text: "Let him who would move the world first move himself.", speaker: "Socrates" },
    // { text: "Contentment is natural wealth, luxury is artificial poverty.", speaker: "Socrates" },
    // { text: "To fear death, gentlemen, is no other than to think oneself wise when one is not, to think one knows what one does not know. No one knows whether death may not be the greatest of all blessings for a man, yet men fear it as if they knew that it is the greatest of evils.", speaker: "Socrates" },
    // { text: "Employ your time in improving yourself by other men's writings so that you shall come easily by what others have labored hard for.", speaker: "Socrates" },
    // { text: "Do not do to others what angers you if done to you by others.", speaker: "Socrates" },
    // { text: "Every action has its pleasures and its price.", speaker: "Socrates" },
    // { text: "We cannot live better than in seeking to become better.", speaker: "Socrates" },
    // { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", speaker: "Socrates" },
    // { text: "Understanding a question is half an answer", speaker: "Socrates" },
    // { text: "Be as you wish to seem.", speaker: "Socrates" },
    // { text: "Thou shouldst eat to live; not live to eat.", speaker: "Socrates" },
    // { text: "One should never do wrong in return, nor mistreat any man, no matter how one has been mistreated by him.", speaker: "Socrates" },
    // { text: "The really important thing is not to live, but to live well. And to live well meant, along with more enjoyable things in life, to live according to your principles.", speaker: "Socrates" },
    // { text: "The easiest and noblest way is not to be crushing others, but to be improving yourselves.", speaker: "Socrates" },
    // { text: "If all our misfortunes were laid in one common heap whence everyone must take an equal portion, most people would be content to take their own and depart.", speaker: "Socrates" },
    // { text: "Those who are hardest to love need it the most.", speaker: "Socrates" },
    // { text: "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", speaker: "Nietzsche" },
    // { text: "That which does not kill us makes us stronger.", speaker: "Nietzsche" },
    // { text: "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.", speaker: "Nietzsche" },
    // { text: "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.", speaker: "Nietzsche" },
    // { text: "You have your way. I have my way. As for the right way, the correct way, and the only way, it does not exist.", speaker: "Nietzsche" },
    // { text: "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.", speaker: "Nietzsche" },
    // { text: "He who has a why to live for can bear almost any how.", speaker: "Nietzsche" },
    // { text: "When we are tired, we are attacked by ideas we conquered long ago.", speaker: "Nietzsche" },
    // { text: "I cannot believe in a God who wants to be praised all the time.", speaker: "Nietzsche" },
    // { text: "The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind.", speaker: "Nietzsche" },
    // { text: "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.", speaker: "Nietzsche" },
    // { text: "No one can construct for you the bridge upon which precisely you must cross the stream of life, no one but you yourself alone.", speaker: "Nietzsche" },
    // { text: "Is man merely a mistake of God's? Or God merely a mistake of man?", speaker: "Nietzsche" },
    // { text: "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.", speaker: "Nietzsche" },
    // { text: "Man is the cruelest animal.", speaker: "Nietzsche" },
    // { text: "Every deep thinker is more afraid of being understood than of being misunderstood.", speaker: "Nietzsche" },
    // { text: "Thoughts are the shadows of our feelings -- always darker, emptier and simpler.", speaker: "Nietzsche" },
    // { text: "A thinker sees his own actions as experiments and questions--as attempts to find out something. Success and failure are for him answers above all.", speaker: "Nietzsche" },
    // { text: "The true man wants two things: danger and play. For that reason he wants woman, as the most dangerous plaything.", speaker: "Nietzsche" },
    // { text: "There are two different types of people in the world, those who want to know, and those who want to believe.", speaker: "Nietzsche" },
    // { text: "All things are subject to interpretation. Whichever interpretation prevails at a given time is a function of power and not truth.", speaker: "Nietzsche" },
    // { text: "Silence is worse; all truths that are kept silent become poisonous.", speaker: "Nietzsche" },
    // { text: "Meaning and morality of One's life come from within oneself. Healthy, strong individuals seek self expansion by experimenting and by living dangerously. Life consists of an infinite number of possibilities and the healthy person explores as many of them as posible. Religions that teach pity, self-contempt, humility, self-restraint and guilt are incorrect. The good life is ever changing, challenging, devoid of regret, intense, creative and risky.", speaker: "Nietzsche" },
    // { text: "What does your conscience say? — 'You should become the person you are'", speaker: "Nietzsche" },
    // { text: "To live is to suffer, to survive is to find some meaning in the suffering.", speaker: "Nietzsche" },
    // { text: "Of all forms of caution, caution in love is perhaps the most fatal to true happiness.", speaker: "Bertrand Russell" },
    // { text: "The fundamental cause of the trouble is that in the modern world the stupid are cocksure while the intelligent are full of doubt.", speaker: "Bertrand Russell" },
    // { text: "I would never die for my beliefs because I might be wrong.", speaker: "Bertrand Russell" },
    // { text: "And if there were a God, I think it very unlikely that He would have such an uneasy vanity as to be offended by those who doubt His existence", speaker: "Bertrand Russell" },
    // { text: "Three passions, simple but overwhelmingly strong have governed my life: the longing for love, the search for knowledge, and unbearable pity for the suffering of mankind.", speaker: "Bertrand Russell" },
    // { text: "In all affairs it's a healthy thing now and then to hang a question mark on the things you have long taken for granted.", speaker: "Bertrand Russell" },
    // { text: "One of the symptoms of an approaching nervous breakdown is the belief that one’s work is terribly important.", speaker: "Bertrand Russell" },
    // { text: "The hardest thing to learn in life is which bridge to cross and which to burn.", speaker: "Bertrand Russell" },
    // { text: "Fear is the main source of superstition, and one of the main sources of cruelty. To conquer fear is the beginning of wisdom.", speaker: "Bertrand Russell" },
    // { text: "It's easy to fall in love. The hard part is finding someone to catch you.", speaker: "Bertrand Russell" },
    // { text: "To teach how to live without certainty, and yet without being paralyzed by hesitation, is perhaps the chief thing that philosophy, in our age, can still do for those who study it.", speaker: "Bertrand Russell" },
    // { text: "It is the preoccupation with possessions, more than anything else, that prevents us from living freely and nobly.", speaker: "Bertrand Russell" },
    // { text: "When you want to teach children to think, you begin by treating them seriously when they are little, giving them responsibilities, talking to them candidly, providing privacy and solitude for them, and making them readers and thinkers of significant thoughts from the beginning. That’s if you want to teach them to think.", speaker: "Bertrand Russell" },
    // { text: "Those who have never known the deep intimacy and the intense companionship of happy mutual love have missed the best thing that life has to give.", speaker: "Bertrand Russell" },
    // { text: "Collective fear stimulates herd instinct, and tends to produce ferocity toward those who are not regarded as members of the herd.", speaker: "Bertrand Russell" },
    // { text: "We know very little, and yet it is astonishing that we know so much, and still more astonishing that so little knowledge can give us so much power.", speaker: "Bertrand Russell" },
    // { text: "It has been said that man is a rational animal. All my life I have been searching for evidence which could support this.", speaker: "Bertrand Russell" },
    // { text: "One should as a rule respect public opinion in so far as is necessary to avoid starvation and to keep out of prison, but anything that goes beyond this is voluntary submission to an unnecessary tyranny, and is likely to interfere with happiness in all kinds of ways.", speaker: "Bertrand Russell" },
    // { text: "The secret of happiness is to face the fact that the world is horrible, horrible, horrible.", speaker: "Bertrand Russell" },
    // { text: "The fact that an opinion has been widely held is no evidence whatever that it is not utterly absurd; indeed in view of the silliness of the majority of mankind, a widely spread belief is more likely to be foolish than sensible.", speaker: "Bertrand Russell" },
    // { text: "I believe that when I die I shall rot, and nothing of my ego will survive.", speaker: "Bertrand Russell" },
    // { text: "Patriots always talk of dying for their country but never of killing for their country.", speaker: "Bertrand Russell" },
    // { text: "The infliction of cruelty with a good conscience is a delight to moralists. That is why they invented Hell.", speaker: "Bertrand Russell" },
    // { text: "Not to be absolutely certain is, I think, one of the essential things in rationality.", speaker: "Bertrand Russell" },
    // { text: "So far as I can remember there is not one word in the Gospels in praise of intelligence.", speaker: "Bertrand Russell" },
    // { text: "The opinions that are held with passion are always those for which no good ground exists; indeed the passion is the measure of the holders lack of rational conviction. Opinions in politics and religion are almost always held passionately.", speaker: "Bertrand Russell" }
];